### ISSUE TITLE
torchScript Export

### ISSUE THREAD

**Issue by paul-ml75** [SysCV/MaskFreeVIS#2]
Hi!

First of all, thanks for this awesome project!
Would it be possible to add a TorchScript export as well? This addition would be extremely helpful for utilizing it with various third-party software.

Thank you,

Paul

**Comment by lkeab** [comment]
Hi, thanks for watching our work. For torchScript Export, since we implement based on detectron2, please refer to the official detectron2 instruction [here](https://detectron2.readthedocs.io/en/stable/_modules/detectron2/export/torchscript.html) and [here](https://detectron2.readthedocs.io/en/latest/tutorials/deployment.html).

**Comment by paul-ml75** [comment]
Oh awesome ! Having a look.

Thank you,
